---
title: "German Criminal Statistics by Nationality"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(shinydashboard)
library(ggplot2)

# Load data
setwd("/Users/kerihartman/Documents/GitHub/DataMan-FinalProject")
load("CrimeDataReduced.Rda")

```

Column {}
-----------------------------------------------------------------------

```{r}

# Define global data frame
lbls <- c("Total", "Violent", "Street", "Robbery and theft", "Murder and manslaughter", 
            "Rape", "Migration", "Drug", "White collar", "Human trafficking", "Cyber")

vars <- c("crtotal", "violent", "street", "robbery", "murder", 
               "rape", "crmig", "crdrug", "whcollar", "htraffic", "cyber")

crimes <- data.frame(cbind(lbls, vars), stringsAsFactors = FALSE)



# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("German Crime Data by Nationality"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
     sidebarPanel(
       selectInput("nat", "Nationality Group:", 
                   choices=unique(dat2$nat)),
       hr(),
       selectInput("var", "Type of Crime:",
                   choices = crimes$lbls),
       hr(),
       helpText("Source: Polizeiliche Kriminalstatistik")
     ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("distPlot")
      )
   )
)

# Define server logic required to draw a histogram

server <- function(input, output) {
   
   output$distPlot <- renderPlot({
      # generate bins based on input$bins from ui.R
     
     plotdat <- dat2[dat2$nat == input$nat, c("year", crimes$vars[crimes$lbls == input$var])]
     names(plotdat)[2] <- "column"
     
     p1 <- ggplot(data = plotdat, mapping = aes(x = year, y = column, group = 1)) + 
       geom_line() + xlab("Year") + ylab("Crimes per 1000 People")
     p1

   })
}

# Run the application 
shinyApp(ui = ui, server = server)

```

